### ISSUE TITLE
Step "Translating BioCypher config leaves to Biolink" fails

### ISSUE THREAD

**Issue by AndiMajore** [saezlab/BioCypher#126]
BioCypher currently crashes on "Translating BioCypher config leaves to Biolink" step, e.g. in clean installation of [OTAR-BioCypher](https://github.com/saezlab/OTAR-BioCypher).

Stack trace:
```INFO -- Translating BioCypher config leaves to Biolink.
Traceback (most recent call last):
  File "/usr/app/scripts/target_disease_script.py", line 150, in <module>
    main()
  File "/usr/app/scripts/target_disease_script.py", line 117, in main
    driver.show_ontology_structure()
  File "/opt/conda/lib/python3.10/site-packages/biocypher/_driver.py", line 777, in show_ontology_structure
    self.start_ontology_adapter()
  File "/opt/conda/lib/python3.10/site-packages/biocypher/_driver.py", line 626, in start_ontology_adapter
    biolink_adapter = BiolinkAdapter(
  File "/opt/conda/lib/python3.10/site-packages/biocypher/_translate.py", line 380, in __init__
    self.main()
  File "/opt/conda/lib/python3.10/site-packages/biocypher/_translate.py", line 449, in main
    self.translate_leaves_to_biolink()
  File "/opt/conda/lib/python3.10/site-packages/biocypher/_translate.py", line 553, in translate_leaves_to_biolink
    self.toolkit.get_ancestors(name_or_synonym, formatted=True),
  File "/opt/conda/lib/python3.10/site-packages/bmt/toolkit.py", line 302, in get_ancestors
    ancs = self.view.class_ancestors(element.name, mixins=mixin, reflexive=reflexive)
  File "/opt/conda/lib/python3.10/site-packages/linkml_runtime/utils/schemaview.py", line 684, in class_ancestors
    return _closure(lambda x: self.class_parents(x, imports=imports, mixins=mixins, is_a=is_a),
  File "/opt/conda/lib/python3.10/site-packages/linkml_runtime/utils/schemaview.py", line 56, in _closure
    vals = f(i)
  File "/opt/conda/lib/python3.10/site-packages/linkml_runtime/utils/schemaview.py", line 684, in <lambda>
    return _closure(lambda x: self.class_parents(x, imports=imports, mixins=mixins, is_a=is_a),
  File "/opt/conda/lib/python3.10/site-packages/linkml_runtime/utils/schemaview.py", line 571, in class_parents
    cls = self.get_class(class_name, imports, strict=True)
  File "/opt/conda/lib/python3.10/site-packages/linkml_runtime/utils/schemaview.py", line 486, in get_class
    c = self.all_classes(imports=imports).get(class_name, None)
  File "/opt/conda/lib/python3.10/site-packages/linkml_runtime/utils/schemaview.py", line 290, in all_classes
    classes = copy(self._get_dict(CLASSES, imports))
  File "/opt/conda/lib/python3.10/site-packages/linkml_runtime/utils/schemaview.py", line 416, in _get_dict
    schemas = self.all_schema(imports)
  File "/opt/conda/lib/python3.10/site-packages/linkml_runtime/utils/schemaview.py", line 235, in all_schema
    return [m[sn] for sn in self.imports_closure(imports)]
  File "/opt/conda/lib/python3.10/site-packages/linkml_runtime/utils/schemaview.py", line 211, in imports_closure
    imported_schema = self.load_import(sn)
  File "/opt/conda/lib/python3.10/site-packages/linkml_runtime/utils/schemaview.py", line 185, in load_import
    schema = load_schema_wrap(sname + '.yaml',
  File "/opt/conda/lib/python3.10/site-packages/linkml_runtime/utils/schemaview.py", line 70, in load_schema_wrap
    schema = yaml_loader.load(path, target_class=SchemaDefinition, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/linkml_runtime/loaders/loader_root.py", line 85, in load
    results = self.load_any(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/linkml_runtime/loaders/yaml_loader.py", line 32, in load_any
    return self.load_source(source, loader, target_class, accept_header="text/yaml, application/yaml;q=0.9",
  File "/opt/conda/lib/python3.10/site-packages/linkml_runtime/loaders/loader_root.py", line 58, in load_source
    data = hbread(source, metadata, metadata.base_path, accept_header)
  File "/opt/conda/lib/python3.10/site-packages/hbreader/__init__.py", line 260, in hbread
    with hbopen(source, open_info, base_path, accept_header, is_actual_data, read_codec) as f:
  File "/opt/conda/lib/python3.10/site-packages/hbreader/__init__.py", line 188, in hbopen
    raise e
  File "/opt/conda/lib/python3.10/site-packages/hbreader/__init__.py", line 184, in hbopen
    response = urlopen(req, context=ssl._create_unverified_context())
  File "/opt/conda/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/conda/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/conda/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/conda/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: https://raw.githubusercontent.com/opt/conda/lib/python3.10/site-packages/linkml_runtime/linkml_model/model/schema/types.yaml```

**Comment by slobentanzer** [comment]
Thanks for the report, @AndiMajore - it appears that this is a connection issue. More specifically, the Biolink Model Toolkit through LinkML tries to connect to some server (identifiers.org or similar) to resolve identifiers or do validation. I have previously had the issue that when some server is down, BioCypher will not build; but I cannot fix this from within BioCypher. 

I have also asked whether they provide offline functionality, and some others seems to have that on their wishlist as well, but so far I am not aware that this is a thing, yet. There is this currently open issue on LinkML: https://github.com/linkml/linkml/issues/1012

Are you trying to build inside an offline environment? If not, maybe a server is down.

I have tagged this as an enhancement, because if LinkML does not provide this functionality in a reasonable time, we can think of a way to build Biolink without BMT entirely. This will be necessary for encapsulation projects in any case. 

We could, for example, build an OBO file from their release files and build the BioCypher-internal network representation from that, as we do with other OBO ontologies. It's more effort in maintenance though, and will not be possible programmatically in Python, because there seems no way to go from the Biolink-provided files to OBO with python only. We'd have to use something like ROBOT to preprocess the Biolink model for each release we want to use. I'd still estimate this as feasible to do in the scope of a project, once at the beginning, and then rely on that build of Biolink for the encapsulated project.

**Comment by slobentanzer** [comment]
@AndiMajore can you update this issue and close if completed?
